export interface DiagnosisResult {
  faultType: string;
  confidence: number;
  solutions: string[];
  description: string;
  severity: 'low' | 'medium' | 'high';
  type?: 'text' | 'image' | 'video' | 'audio';
  timestamp?: Date;
  fileName?: string;
  analysisType?: 'single-image' | 'multi-image' | 'video-analysis' | 'text-analysis' | 'audio-analysis' | 'error';
  // 兼容旧字段
  issues?: string[];
  recommendations?: string[];
  summary?: string;
}

export interface Statistics {
  totalFrames: number;
  analyzedFrames: number;
  abnormalFrames: number;
  abnormalRatio: number;
  duration: number;
  // 兼容旧字段
  totalTests?: number;
  passedTests?: number;
  failedTests?: number;
  warningTests?: number;
}

export interface FrameAnalysis {
  frameNumber: number;
  timestamp: number;
  anomalyType: 'vibration' | 'noise' | 'visual' | 'normal';
  confidence: number;
  severity: 'low' | 'medium' | 'high';
  description: string;
  detectedFeatures: {
    brightness: number;
    contrast: number;
    motionIntensity: number;
    pixelAnomalies: number;
  };
}

export interface PaperInfo {
  title: string;
  authors: string[];
  date: string;
  abstract: string;
  url: string;
  source: 'arxiv' | 'pubmed' | 'local';
  category?: string;
  keywords?: string[];
}

export interface MaterialItem {
  id: string;
  name: string;
  type: 'document' | 'image' | 'video' | 'audio' | 'diagnosis' | 'text' | 'web' | 'diagnosis_log';
  size: number | string;
  uploadDate: Date | string;
  tags: string[];
  description?: string;
  content?: string;
  imagePreview?: string;
  file?: File;
  diagnosisResult?: DiagnosisResult;
  analysisData?: any;
  title?: string;
  url?: string;
  authors?: string;
  source?: string;
  category?: string;
  autoIntegrated?: boolean;
  createdAt?: Date | string;
  importance?: 'low' | 'medium' | 'high';
}

export interface SearchResult {
  id: string;
  title: string;
  authors: string[];
  abstract: string;
  publishedDate: string;
  source: string;
  url: string;
  relevanceScore: number;
}

export interface Node {
  id: string;
  label: string;
  category: string;
  size: number;
  color: string;
}

export interface Edge {
  source: string;
  target: string;
  weight: number;
  label?: string;
}

export interface GraphData {
  nodes: Node[];
  edges: Edge[];
}

export interface CustomLogo {
  id: string;
  name: string;
  url: string;
  position: 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right';
  size: 'small' | 'medium' | 'large';
  opacity: number;
  path: string;
  uploadDate?: string;
}

// 图片分析相关类型
export interface ImageAnalysis {
  region: {
    x: number;
    y: number;
    width: number;
    height: number;
  };
  description: string;
  confidence: number;
  anomalyType: 'corrosion' | 'crack' | 'loose' | 'wear' | 'leak' | 'normal' | 'other';
  severity: 'low' | 'medium' | 'high';
  solution: string;
  detailedDescription: string;
}

export interface SingleImageAnalysis {
  fileName: string;
  fileSize: number;
  analysisResults: ImageAnalysis[];
  overallDescription: string;
  primaryIssues: string[];
  recommendations: string[];
}

export interface MultiImageAnalysis {
  individualAnalyses: SingleImageAnalysis[];
  overallSummary: string;
  commonIssues: string[];
  rootCauseAnalysis: RootCauseAnalysis[];
  prioritizedSolutions: PrioritizedSolution[];
}

export interface RootCauseAnalysis {
  category: string;
  description: string;
  affectedImages: number[];
  severity: 'low' | 'medium' | 'high';
  confidence: number;
}

export interface PrioritizedSolution {
  priority: number;
  title: string;
  description: string;
  estimatedCost: 'low' | 'medium' | 'high';
  timeToImplement: 'immediate' | 'short-term' | 'long-term';
  effectivenessScore: number;
  affectedIssues: string[];
}

// 诊断日志类型
export interface DiagnosisLog {
  id: string;
  type: 'text' | 'image' | 'video' | 'audio' | 'multi-image';
  title: string;
  fileName: string;
  analysisDate: Date;
  result: DiagnosisResult;
  multiImageAnalysis?: MultiImageAnalysis;
  tags: string[];
  severity: 'low' | 'medium' | 'high';
  autoGenerated: boolean;
}

export interface AnalysisResponse {
  analysis: DiagnosisResult;
  statistics?: Statistics;
}

export interface TextAnalysisResponse {
  analysis: DiagnosisResult;
  statistics?: Statistics;
}

export interface VideoAnalysisResponse {
  analysis: DiagnosisResult;
  statistics: Statistics;
}

export interface VideoInputProps {
  onVideoUpload: (file: File) => Promise<void>;
  onFrameCapture?: () => void;
}

export interface DiagnosisResultProps {
  result: string;
  statistics?: Statistics;
}

// 知识库文档接口
export interface KnowledgeDocument {
  id: string;
  title: string;
  content: string;
  category: string;
  tags: string[];
  createdAt: string;
  relatedDocuments: string[];
} 